---
engines:
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - ruby
  fixme:
    enabled: true
  rubcop:
    enabled: true
ratings:
  paths: 
    - "**.rb"
    - "getips"
exclude_paths:
  - ".rvmrc"
  - "**.swp"
  - "**~"
